# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c992b7131cbaa1ab2de21858af1bcdf23ef4d97b1d64901ce7639293d3da63c407ae2a07c099dfda7aadb4930683cbb0c8cc88e799ceae997717d3aedfba0fde

test:
  secret_key_base: dc494fcbd119c23d8a5f7a5d413a96ff9884162077b5b49de8f49faa1974b9a2b1802ae41174d8f3eddf9c5789ecca330083f9450a3ed95ca39f39b2b0a3a23a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
